SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(C.TOTAL_COUNT * B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A USING (AUTHOR_ID)
JOIN (
    SELECT
        BOOK_ID,
        SUM(SALES) AS TOTAL_COUNT
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE)=2022
      AND MONTH(SALES_DATE)=1
    GROUP BY BOOK_ID
) C USING (BOOK_ID)
GROUP BY
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY
ORDER BY
    B.AUTHOR_ID,
    B.CATEGORY DESC;